version: '3.7'

services:
  app:
    image: shoppingcart
    container_name: shoppingcart
    ports:
      - "8000:8000"
    restart: always
    networks:
      - shoppingcart-network
    environment:
      SPRING_PROFILES_ACTIVE: local
      WAIT_HOSTS_TIMEOUT: 320
      WAIT_SLEEP_INTERVAL: 10
      WAIT_AFTER_HOSTS: 30
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - shoppingcart-network

networks:
  shoppingcart-network:
    driver: bridge

volumes:
  postgres-data: